sekolah_kita_server/backoffice/province/urls.py
from django.conf.urls import url 
from .views import index, details, add_province, edit_province

app_name = 'province'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^(?P<id>\d+)$', details, name='details'),
    url(r'^add_province/$', add_province, name='add_province'),
    url(r'^(?P<id>\d+)/edit_province/$', edit_province, name='edit_province'),
]

sekolah_kita_server/backoffice/urls.py
from django.conf.urls import url, include
from django.conf import settings
from .views import login_view, logout_view


app_name = 'backoffice'

urlpatterns = [
    url(r'^$', login_view, name='login_view'),
    #url(r'^login$', login_view, name='login_view'),
    url(r'^logout$', logout_view, name='logout_view'),
    url(r'^dashboard/', include('sekolah_kita_server.backoffice.province.urls')),
]

sekolah_kita_server/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^$', include('sekolah_kita_server.backoffice.urls')),
    url('backoffice/', include('sekolah_kita_server.backoffice.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sekolah_kita_server/apps/province/models.py
from django.db import models


class Province(models.Model):
    kode_provinsi = models.CharField(max_length=5)
    province_name = models.CharField(max_length=200)
    logo_provinsi = models.FileField()

sekolah_kita_server/apps/sekolah/models.py
from django.db import models

# Create your models here.

sekolah_kita_server/apps/users/models.py
from django.db import models

# Create your models here.

sekolah_kita_server/apps/province/views.py
from django.shortcuts import render

# Create your views here.

sekolah_kita_server/apps/sekolah/views.py
from django.shortcuts import render

# Create your views here.

sekolah_kita_server/apps/users/views.py
from django.shortcuts import render

# Create your views here.

sekolah_kita_server/backoffice/province/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from sekolah_kita_server.apps.province.models import Province
from sekolah_kita_server.core.decorators import user_staff_required
from sekolah_kita_server.apps.province.form import ProvinceForm


@user_staff_required
def index(request):
    provinces = Province.objects.order_by('id').all()
    page = request.GET.get('page', 1)

    paginator = Paginator(provinces, 20)
    try:
        page = paginator.page(page)
    except PageNotAnInteger:
        page = paginator.page(1)
    except EmptyPage:
        page = paginator.page(paginator.num_page)

    context_data = {
        'title': 'Provinsi',
        'page': page
    }
    return render(request, 'backoffice/province/index.html', context_data)


def details(request, id):
    province = get_object_or_404(Province.objects.all(), id=id)
    context_data = {
        'province': province,
    }
    return render(request, 'backoffice/province/details.html', context_data)


def add_province(request):
    form = ProvinceForm(request.POST or None, request.FILES or None)
    if request.method == "POST":
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('backoffice:province:index')
    else:
        form = ProvinceForm()
    context_data = {
        'form': form
    }
    return render(request, 'backoffice/province/province_form.html',context_data)


def edit_province(request, id):
    province = get_object_or_404(Province.objects.all(), id=id)
    if request.method == "POST":
        form = ProvinceForm(request.POST or None, request.FILES or None, instance=province)
        if form.is_valid():
            province = form.save(commit=False)
            province.save()
            return redirect('backoffice:province:index')
    else:
        form = ProvinceForm(instance=province)
    context_data = {
        'form': form,
    }        
    return render(request, 'backoffice/province/province_form.html', context_data)

sekolah_kita_server/backoffice/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect, render
from django.contrib.auth import login, logout
from sekolah_kita_server.core.decorators import user_staff_required


def login_view(request):
    auth_form = AuthenticationForm(data=request.POST or None)
    if auth_form.is_valid():
        login(request, auth_form.get_user())
        return redirect('backoffice:province:index')
    
    context_data = {
        'form': auth_form,
        'title': 'Login',
    }
    return render(request, 'backoffice/login.html', context_data)


def logout_view(request):
    logout(request)
    return redirect('backoffice:login_view')

templates/backoffice/base.html
{% load static %}
<html>
    <head>
        <title>Sekolah Kita</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'backoffice/styles.css' %}">
    </head>
    <body>
    <div class="container-fluid">
        <div class="page-header">
            <h1>Sekolah Kita</h1>
        
            <div class="nav_wrapper">
                <ul class="nav nav-pills">
                    <li class="{% if current_page == 'users' %}active{% endif %}">
                        <a href="">Sekolah</a>
                    </li>
                    <li class="{% if current_page == 'repayments' %}active{% endif %}">
                        <a href="">Provinsi</a>
                    </li>
                    <li>
                        <a href="{% url 'backoffice:logout_view' %}" class="green">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </div>
</body>

</html>

templates/backoffice/login.html
<!DOCTYPE html>
<html>
	<head>
		<title></title>
	</head>
<body>
	<h3>Login</h3>
	<form method="POST">
		{% csrf_token %}
		<div>
			<label>Username :</label>
			<input type="text" name="username">
		</div>
		<div>
			<label>Password :</label>
			<input type="password" name="password">
		</div>
		<div>
			<input type="submit" value="Submit">
		</div>
	</form>
</body>
</html>

templates/backoffice/province/details.html
{% extends 'backoffice/base.html' %}
{% block content %}
<button type="button" onclick="location.href='{% url 'backoffice:province:edit_province' province.id %}'" class="btn btn-primary">Edit</button>
<div id='head'>
<img src={{province.logo_provinsi.url}} height='100px' width='100px'>
<h1>{{province.province_name}} </h1>
</div>
{% endblock content %}

templates/backoffice/province/index.html
{% extends 'backoffice/base.html' %}

{% block content %}
<div class="title">
    <h1> Daftar Provinsi </h1>
</div>
<button type="button" onclick="location.href='{% url 'backoffice:province:add_province' %}'" class="btn btn-primary">Tambah</button>
<table class='table'>
  <thead class="thead-light">
    <tr>
        <th>Kode Provinsi</th>
        <th>Nama Provinsi</th>
        <th></th>
    </tr>
    </thead>
    {% for provinsi in page.object_list %}
    <tr>
        <td><a href={% url 'backoffice:province:details' provinsi.id %}>{{ provinsi.kode_provinsi }}</td>
        <td>{{ provinsi.province_name }}</td>
        {% if provinsi.logo_provinsi%}
        <td><img src='{{ provinsi.logo_provinsi.url }}' height="40px" width="40px"></td>
        {% endif %}
    </tr>
    {% endfor%}
</table>
{% if page.has_other_pages %}
    <ul class="pagination">
        {% if page.has_previous %}
            <li><a href="?page={{ page.previous_page_number }}">&laquo; Previous</a></li>
        {% endif %}
        <li>
            Page {{ page.number }} of {{ page.paginator.num_pages }}
        </li>
        {% if page.has_next %}
            <li><a href="?page={{ page.next_page_number }}">Next &raquo;</a></li>
        {% endif %}
    </ul>
{% endif %}

{% endblock %}

templates/backoffice/province/province_form.html
{% extends 'backoffice/base.html' %}

{% block content %}
    <h1>Tambah Provinsi</h1>
    <form method="POST" enctype='multipart/form-data' class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}